language: r

# http://docs.travis-ci.com/user/languages/r/

sudo: required
r_binary_packages:
 - doparallel 
 - dplyr 
 - scales
 - teachingdemos
 - stringi
 - coda
 - mvtnorm
 - stringr
 - gtools
 - matrixmodels
 - rcppeigen
r_packages:
 - BayesFactor  

warnings_are_errors: false
