language: r

# http://docs.travis-ci.com/user/languages/r/

before_install:
 - cd package

sudo: required
r_binary_packages:
 - doparallel 
 - dplyr 
 - scales
 - teachingdemos
 - stringi
 - coda
 - mvtnorm
 - stringr
 - gtools
 - matrixmodels
 - rcppeigen
r_packages:
 - BayesFactor  
 - covr

warnings_are_errors: false

# only report coverage after build is successful
# not yet - takes too long
#after_success:
#  - Rscript -e 'covr::codecov()'